### ISSUE TITLE
Hi there is no actual issue but my peanut brain cant comprend this pls help and sorry to disturb you

### ISSUE THREAD

**Issue by Geneticlord** [vic1707/AutoPlay-PokeMeow-Discord#32]
![unknown (6)](https://user-images.githubusercontent.com/94822489/142809088-ba624452-d662-45d1-b3ce-bed1bc0e9251.png)

**Comment by vic1707** [comment]
once you've cloned the repo (maybe by downloading a zip) 
extract it to the folder of your choice and open CMD(windows) or the terminal (Linux/Mac)
and type (or copy paste) 
`python -m pip install -r requirements.txt` if you're on Windows
`python3 -m pip install -r requirements.txt` if you're on Linux/Mac

**Comment by Geneticlord** [comment]
I tried what you told but it gave me this error
![image](https://user-images.githubusercontent.com/94822489/143221715-04641e95-c7d5-488c-b5db-8f7cb41ac31f.png)

**Comment by vic1707** [comment]
is your cmd promt in the right directory? -> are the .py files under `C:\Users\vella` ? I would assume they are somewhere in the downloads directory. If I'm right you're executing the right command in a wrong directory

open the file explorer and navigate to the folder containing all the files from the bot, then click on the right of the folder name in order to be able to type `cmd` in the search bar
![image](https://user-images.githubusercontent.com/28602203/143267178-2538a47f-cdb2-4748-a18b-04e788b1c8bb.png)
when cmd opens you should be able to execute the commands

**Comment by Geneticlord** [comment]
oh ok thx

**Comment by vic1707** [comment]
Working now? Can we close the issue?
